site_name: BigFunctions
repo_name: 'unytics/bigfunctions'
repo_url: 'https://github.com/unytics/bigfunctions'
edit_uri: 'edit/main'
copyright: 'Copyright &copy; 2024 Unytics'
docs_dir: '..'
exclude_docs: |
  /venv/
  /.venv/
site_dir: '../../bigfunctions_website'
extra_css:
  - site/stylesheets/extra.css
theme:
  name: material
  custom_dir: overrides
  logo: site/assets/logo.png
  favicon: site/assets/logo.png
  features:
    - tabs
    - content.tabs.link
    - content.code.copy
    # - instant
    # - toc.integrate
    # - navigation.instant
    - navigation.path
    - navigation.tabs
    - navigation.tracking
    - navigation.indexes
    - navigation.hide
    # - navigation.expand
markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - toc:
      toc_depth: 4
      permalink: "¶"
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - awesome-pages
  - search
nav:
  - Get Started!: README.md
  - ... | regex=.*README.md
